### PR TITLE
publish all slack events to redis

### PR DESCRIPTION
**Pull request by phallstrom**
This patch will publish all slack event webhook params to Redis' pubsub
channel 'slack_events'. Right now this serves no purpose, but it will
allow us to subscribe to that channel and see the actual event data
making it easier to develop additional functionality.

My long range plan is to add a standalone CLI app that when run will
subscribe, listen, and "repost" the events to your local development
server.

### CODE REVIEW

**Comment by phallstrom** [comment]
Here's an example of the raw output that I've wired up using the railslink-dev slack team.

```
1) "message"
2) "slack_events"
3) "{\"token\":\"xxxx\",\"team_id\":\"xxx\",\"api_app_id\":\"xxx\",\"event\":{\"type\":\"message\",\"user\":\"UCFC0B6E9\",\"text\":\"testing one two\",\"client_msg_id\":\"41a7d87a-41d9-47e7-81b4-bf47867c6621\",\"ts\":\"1540752076.002200\",\"channel\":\"CCEFW4DMW\",\"event_ts\":\"1540752076.002200\",\"channel_type\":\"channel\"},\"type\":\"event_callback\",\"event_id\":\"EvDPEBT9B2\",\"event_time\":1540752076,\"authed_users\":[\"UCFC0B6E9\"]}"
```

**Comment by brandondees** [comment]
This code seems fine, but I'm not sure if I understand what security/privacy implications this might have. Care to elaborate on that side of things @phallstrom ?

**Comment by phallstrom** [comment]
@brandondees Sure.  Currently we send team-join, channel-join, and chat-message slack events to the website.  We've done that for awhile.  This extends that to publish those params via our Redis instance.  Mostly so that as we develop we can subscribe and see the exact payload we'll need to develop against.

Privacy information would include your Slack user info (whatever you've provided) and the contents of your chat message.  Only those people that have the Redis connection information could see it however.  For those of us already in the Slack team it wouldn't be any more than we could get right now just lurking.

My personal plan is to use it to watch the railslink-dev slack team while I develop other integrations.

**Comment by brandondees** [comment]
How is it authenticated?

**Comment by phallstrom** [comment]
Standard Redis user/pass over HTTPS.  It's a single user/pass for everyone.  Same values that are in heroku's env var config.

**Comment by brandondees** [comment]
Hmm, ok. So it could be a lot stronger but probably not going to be a serious risk for now.

**Pull request merged**
