### PR TITLE
Upgraded Ruby, Rails, misc. gems and Gemfile's source line

### PR DESCRIPTION
**Pull request by jasnow**
Summary of Changes

 1. Changed "http" to "https" on Gemfile's source line.
 1. Upgraded Ruby to 2.2.3.
 1. Upgraded Rails to 4.2.4 along with other gem upgrades.
 1. Added .overcommit.yml to .gitignore to not force use in repo.

Hope this helps...

### CODE REVIEW

**Comment by jasnow** [comment]
It is always helpful to add a comment when you reject a pull request.

**Comment by moriokumura** [comment]
Sorry for the lack of explanation. The previous master branch, to which you made pull request had some problem and I reverted it. That operation automatically triggered the closing of this pull request.

Actually, I didn't reject your pull request. I'm looking into this now.
But because the branch history that your pull request depends on has been modified, we need a new pull request for the current master branch. I'm sorry for your additional work, but would you re-create the pull request containing the changes you intended?

**Comment by jasnow** [comment]
Looks like SLACK_API_TOKEN env variable is a dependency to run tests now. My test run is not green yet.

**Comment by moriokumura** [comment]
You can get your Slack API token at https://api.slack.com/web#authentication
then make `.env` file on project root, and add the line

```
SLACK_API_TOKEN=your-slack-api-token
```

**Comment by jasnow** [comment]
After logging in to my https://rubyonrails-link.slack.com 
account and refreshing the above link, I get this:

**rubyonrails 	jasnow 	Usage of the Slack API has been disabled by this team's admin.**

Which slack account should I be logged into?

**Comment by moriokumura** [comment]
I changed a setting. Do you still see the same message?

**Comment by jasnow** [comment]
Got token. Now to use it. THANKS !!!

**Comment by jasnow** [comment]
How does CircleCI get SLACK_API_TOKEN value?

**Comment by moriokumura** [comment]
We set it from web UI of CircleCI.

**Pull request closed without merging**
