### PR TITLE
tweak marginalia config so it ignores ruby's monitor.rb stack frame

### PR DESCRIPTION
**Pull request by phallstrom**
Marginalia and Ruby 2.4/2.5 have an issue where the stack trace includes
Ruby's own monitor.rb and this isn't excluded by the default
configuration so it shows all SQL queries as coming from there. This
patch adds it to the exclusion list.

See https://github.com/basecamp/marginalia/issues/70

test plan:
  - fire up rails server and watch the logs
  - load up the homepage
  - notice that the SQL comments appropriately show where they are
    invoked instead of pointing to monitor.rb

### CODE REVIEW

**Comment by arku** [comment]
@phallstrom Interesting. I tried running the rails server from `master` and noticed the logs. The stack trace was fine. Here are the logs.

```
Started GET "/" for 127.0.0.1 at 2019-05-26 16:59:52 -0500
   (0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by HomeController#index as HTML
   (17.7ms)  SELECT COUNT(*) FROM "slack_users" WHERE "slack_users"."is_deleted" = $1 AND "slack_users"."is_bot" = $2 /*controller_with_namespace:HomeController,action:index,line:/app/controllers/home_controller.rb:3:in `index'*/  [["is_deleted", "f"], ["is_bot", "f"]]
  SlackChannel Load (8.6ms)  SELECT "slack_channels".* FROM "slack_channels" WHERE "slack_channels"."is_private" = $1 AND "slack_channels"."is_archived" = $2 ORDER BY "slack_channels"."members_count" DESC /*controller_with_namespace:HomeController,action:index,line:/app/controllers/home_controller.rb:4:in `index'*/  [["is_private", "f"], ["is_archived", "f"]]
   (1.5ms)  SELECT COUNT(*) AS count_all, tz_offset / 3600 AS tz_offset_3600 FROM "slack_users" WHERE ("slack_users"."tz_offset" IS NOT NULL) GROUP BY tz_offset / 3600 /*controller_with_namespace:HomeController,action:index,line:/app/models/slack_user.rb:48:in `tz_offset_distribution'*/
```

Not sure if I am missing something.

**Comment by katelovescode** [comment]
> @phallstrom Interesting. I tried running the rails server from `master` and noticed the logs. The stack trace was fine. Here are the logs.
> 
> ```
> Started GET "/" for 127.0.0.1 at 2019-05-26 16:59:52 -0500
>    (0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
> Processing by HomeController#index as HTML
>    (17.7ms)  SELECT COUNT(*) FROM "slack_users" WHERE "slack_users"."is_deleted" = $1 AND "slack_users"."is_bot" = $2 /*controller_with_namespace:HomeController,action:index,line:/app/controllers/home_controller.rb:3:in `index'*/  [["is_deleted", "f"], ["is_bot", "f"]]
>   SlackChannel Load (8.6ms)  SELECT "slack_channels".* FROM "slack_channels" WHERE "slack_channels"."is_private" = $1 AND "slack_channels"."is_archived" = $2 ORDER BY "slack_channels"."members_count" DESC /*controller_with_namespace:HomeController,action:index,line:/app/controllers/home_controller.rb:4:in `index'*/  [["is_private", "f"], ["is_archived", "f"]]
>    (1.5ms)  SELECT COUNT(*) AS count_all, tz_offset / 3600 AS tz_offset_3600 FROM "slack_users" WHERE ("slack_users"."tz_offset" IS NOT NULL) GROUP BY tz_offset / 3600 /*controller_with_namespace:HomeController,action:index,line:/app/models/slack_user.rb:48:in `tz_offset_distribution'*/
> ```
> 
> Not sure if I am missing something.

I had the same experience.  I'm not seeing anything pointing to `monitor.rb` on the develop branch, so I can't compare the reported existing behavior.  I tried loading the website homepage and also the admin dashboard, and got the same results, no record of `monitor.rb` in the server logs.

**Comment by phallstrom** [comment]
Super weird. I know it's a problem as I hit it at work and I swear I saw it here too, but now I can't repro. I wonder if in my hacking I ended up using ruby 2.5.5 for a bit.  Hrm.  Would you be opposed to approving it on the grounds that it doesn't break anything?

**Comment by arku** [comment]
> Would you be opposed to approving it on the grounds that it doesn't break anything?

@phallstrom Not at all! :slightly_smiling_face:

**Pull request merged**
